"""Test: the bandwidth table in the morphology doc still matches the code.

The table in section 7.2c of docs/drone_morphology_gate_racing.md is generated by
docs/tools/principal_axes_table.py. An earlier hand-computed version of it could
not be reproduced -- the bodies were never specified and one row was wrong -- so
the committed CSV is pinned here. If a change to the inertia or decoder path
moves these numbers, this fails and the doc gets regenerated rather than
silently drifting.
"""

# Standard library
import csv
from pathlib import Path

# Third-party libraries
import numpy as np
import pytest

# Local libraries
import sys

REPO = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO / "docs" / "tools"))

import principal_axes_table as pat  # noqa: E402

CSV = REPO / "docs" / "data" / "principal_axes.csv"
CSV_SENS = REPO / "docs" / "data" / "principal_axes_sensitivity.csv"
DOC = REPO / "docs" / "drone_morphology_gate_racing.md"


def _committed(path: Path = CSV) -> list[dict]:
    with path.open() as fh:
        return list(csv.DictReader(fh))


def test_regenerated_matches_committed_csv() -> None:
    """The generator still produces the numbers behind the published table."""
    fresh, committed = pat.rows(), _committed()
    assert [r["body"] for r in fresh] == [r["body"] for r in committed]
    for f, c in zip(fresh, committed):
        for key in ("max_off_diagonal", "diag_wn_min", "diag_wn_max",
                    "matrix_wn_min", "matrix_wn_max", "I1", "I2", "I3",
                    "misalignment_deg"):
            assert float(c[key]) == pytest.approx(f[key], rel=1e-6, abs=1e-12), (
                f"{f['body']}: {key} drifted from the committed CSV -- "
                f"rerun docs/tools/principal_axes_table.py and update the doc")


def test_sensitivity_regenerated_matches_committed_csv() -> None:
    """The Ixy-perturbation sweep behind the conditioning argument still holds."""
    fresh, committed = pat.sensitivity_rows(), _committed(CSV_SENS)
    assert len(fresh) == len(committed)
    for f, c in zip(fresh, committed):
        for key in f:
            assert float(c[key]) == pytest.approx(f[key], rel=1e-6, abs=1e-12), (
                f"I_xy={f['I_xy']}: {key} drifted -- rerun the generator")


def test_markdown_tables_are_present_in_the_doc() -> None:
    """Every rendered table in section 7.2c is the one the generator emits."""
    doc, rows = DOC.read_text(), pat.rows()
    for name, table in (
        ("bandwidth", pat.markdown(rows)),
        ("principal moments", pat.markdown_principal(rows)),
        ("Ixy sensitivity", pat.markdown_sensitivity(pat.sensitivity_rows())),
    ):
        assert table.strip() in doc, f"{name} table in the doc is stale"


def test_misalignment_is_ill_conditioned_but_the_dynamics_are_not() -> None:
    """The claim the conditioning argument rests on, checked directly.

    A coupling small enough to be dynamically negligible still swings the
    principal axes across most of their range. That asymmetry is the reason the
    controller uses K_R = wn^2 I rather than adopting the principal frame.
    """
    small = next(r for r in pat.sensitivity_rows() if r["I_xy"] == 1e-5)
    bandwidth_shift = max(abs(small["diag_wn_min"] - pat.WN),
                          abs(small["diag_wn_max"] - pat.WN)) / pat.WN
    assert bandwidth_shift < 0.01, "expected a dynamically negligible coupling"
    assert small["misalignment_deg"] > 25.0, "expected a large axis swing"


def test_matrix_gains_recover_the_target_on_every_body() -> None:
    """K_R = wn^2 I gives I^-1 K_R = wn^2 * 1, for any symmetric positive-definite I.

    This is the claim the section rests on, so it is checked directly rather
    than read off the table.
    """
    for name, inertia in pat.bodies().items():
        assert np.allclose(inertia, inertia.T), f"{name}: inertia not symmetric"
        assert np.all(np.linalg.eigvalsh(inertia) > 0), f"{name}: not positive-definite"
        wn = pat.bandwidth(inertia, matrix_gains=True)
        assert np.allclose(wn, pat.WN, atol=1e-9), f"{name}: got {wn}"


def test_diagonal_gains_split_the_bandwidth_when_axes_are_not_principal() -> None:
    """The instrument discriminates: no spread on the principal body, spread off it."""
    spread = {
        name: float(np.ptp(pat.bandwidth(I, matrix_gains=False)))
        for name, I in pat.bodies().items()
    }
    principal = "symmetric X quad (swept family)"
    assert spread[principal] < 1e-9
    for name, s in spread.items():
        if name != principal:
            assert s > 1.0, f"{name}: expected a visible spread, got {s}"
