#!/usr/bin/env python3
"""Which axis of the gyroscopic coupling produces the corrected model's reversal?

    uv run --no-sync python docs/tools/gyroscopic_axis_attribution.py AXES OUT.json
    uv run --no-sync python docs/tools/gyroscopic_axis_attribution.py summarise DIR OUT.md

AXES is one of none | x | y | z | all. The data are in
docs/data/gyroscopic_axis_attribution/ (one JSON per condition) and summarised in
docs/data/gyroscopic_axis_attribution.md.

Why. On the corrected model wide frames beat narrow ones at 90 and 120 deg, the
reverse of the reduced model, and the counterfactual (gyroscopic_counterfactual.py)
showed the gyroscopic term causes it. For this planar family Izz is the same for
every frame and about Ixx + Iyy, so in Euler's equations the roll and pitch
gyroscopic accelerations are nearly geometry-independent (p_dot ~ -qr, q_dot ~ pr)
and only the yaw one, r_dot = (Ixx - Iyy)/Izz * pq, changes with geometry -- and it
changes sign across the family. This asks which axis carries the effect.

How. Runs on the corrected plant (commit df7bfda), where both the plant's
-Omega x I Omega and the controller's +Omega x I Omega cancellation act on all
three body axes. On every axis NOT listed in AXES, both are removed, so that axis
behaves as if neither model had the term. `all` is the unpatched corrected model
and must reproduce docs/data/tuned_strict_completion.csv cell for cell (it did,
6/6). Bodies t = 20.44 (narrow), 45.00 (X), 69.56 (wide); turns 90 and 120 deg;
Table 1 operating point.

PRE-REGISTERED 2026-09-17, before any data (hypothesis-divergence session). Gap =
limit(none) - limit(all) for the narrow frame (a loss); limit(all) - limit(none)
for the wide frame (a gain).
  An axis REPRODUCES the narrow loss if limit(none) - limit(axis) >= 0.5 x gap at
  BOTH 90 and 120. It REPRODUCES the wide gain if limit(axis) - limit(none) >= 0.5 x
  gap at every turn where that gap exceeds 0.125 m/s (two bisection tolerances).
  H-yaw         : z reproduces both the narrow loss and the wide gain.
  H-pitch       : y reproduces the narrow loss and not the wide gain.
  H-interaction : no single axis reproduces the narrow loss.
Result (2026-09-17): H-yaw SUPPORTED; H-pitch and H-interaction REFUTED.
"""
from __future__ import annotations

import csv
import json
import sys
import warnings
from pathlib import Path

import numpy as np

warnings.simplefilter("ignore")
REPO = Path(__file__).resolve().parents[2]
CONDITIONS = ("none", "x", "y", "z", "all")
HALVES = (20.44, 45.00, 69.56)
TURNS = (90.0, 120.0)
TABLE_CORRECTED = REPO / "docs" / "data" / "tuned_strict_completion.csv"


def score(runs: dict[str, dict]) -> dict:
    """Pre-registered scoring. Returns coverage per axis and the three verdicts."""
    def s(c: str, turn: float, h: float) -> float:
        return runs[c][f"{turn:.0f}@{h:.2f}"]["max_speed"]

    out: dict = {"axes": {}}
    for axis in ("x", "y", "z"):
        loss, gain = [], []
        for turn in TURNS:
            gap = s("none", turn, 20.44) - s("all", turn, 20.44)
            got = s("none", turn, 20.44) - s(axis, turn, 20.44)
            loss.append({"turn": turn, "gap": gap, "covered": got,
                         "fraction": got / gap, "reproduces": gap > 0 and got >= 0.5 * gap})
            gap_w = s("all", turn, 69.56) - s("none", turn, 69.56)
            got_w = s(axis, turn, 69.56) - s("none", turn, 69.56)
            gain.append({"turn": turn, "gap": gap_w, "covered": got_w,
                         "fraction": got_w / gap_w if gap_w else float("nan"),
                         "reproduces": None if gap_w <= 0.125 else got_w >= 0.5 * gap_w})
        scored = [g["reproduces"] for g in gain if g["reproduces"] is not None]
        out["axes"][axis] = {
            "loss": loss, "gain": gain,
            "reproduces_loss": all(x["reproduces"] for x in loss),
            "reproduces_gain": bool(scored) and all(scored),
        }
    ax = out["axes"]
    out["H-yaw"] = "SUPPORTED" if ax["z"]["reproduces_loss"] and ax["z"]["reproduces_gain"] else "REFUTED"
    out["H-pitch"] = ("SUPPORTED" if ax["y"]["reproduces_loss"] and not ax["y"]["reproduces_gain"]
                      else "REFUTED")
    out["H-interaction"] = ("SUPPORTED" if not any(ax[a]["reproduces_loss"] for a in ("x", "y", "z"))
                            else "REFUTED")
    return out


def summarise(d: Path) -> str:
    runs = {c: json.loads((d / f"{c}.json").read_text()) for c in CONDITIONS}
    table3 = {f"{float(r['turn_deg']):.0f}@{float(r['half_angle_deg']):.2f}": float(r["max_speed"])
              for r in csv.DictReader(open(TABLE_CORRECTED))}
    bad = [(c, k) for c in CONDITIONS for k, v in runs[c].items()
           if not v["monotone"] or v["bracket"] != "ok"]
    mismatch = [k for k, v in runs["all"].items() if v["max_speed"] != table3[k]]
    lines = [
        "Generated by `uv run --no-sync python docs/tools/gyroscopic_axis_attribution.py "
        "summarise docs/data/gyroscopic_axis_attribution docs/data/gyroscopic_axis_attribution.md`.",
        "Criteria are in the tool's docstring (pre-registered 2026-09-17).", "",
        f"Validity: {sum(len(r) for r in runs.values())} bisections, non-monotone or bad bracket: "
        f"{len(bad)}; `all` differs from Table 3 on {len(mismatch)} of {len(runs['all'])} cells.", "",
        "Max completing speed (m/s), gyroscopic term kept only on the listed axes:", "",
        "| turn | t (deg) | none | x (roll) | y (pitch) | z (yaw) | all |",
        "|---|---|---|---|---|---|---|"]
    for turn in TURNS:
        for h in HALVES:
            k = f"{turn:.0f}@{h:.2f}"
            lines.append(f"| {turn:.0f}° | {h:.2f} | " +
                         " | ".join(f"{runs[c][k]['max_speed']:.3f}" for c in CONDITIONS) + " |")
    sc = score(runs)
    lines += ["", "| axis | share of narrow loss, 90° / 120° | share of wide gain, 120° | "
                  "reproduces loss | reproduces gain |", "|---|---|---|---|---|"]
    for axis in ("x", "y", "z"):
        a = sc["axes"][axis]
        g120 = next(g for g in a["gain"] if g["turn"] == 120.0)
        lines.append(f"| {axis} | {100 * a['loss'][0]['fraction']:.0f}% / "
                     f"{100 * a['loss'][1]['fraction']:.0f}% | {100 * g120['fraction']:.0f}% | "
                     f"{a['reproduces_loss']} | {a['reproduces_gain']} |")
    lines += ["", f"H-yaw: **{sc['H-yaw']}**. H-pitch: **{sc['H-pitch']}**. "
                  f"H-interaction: **{sc['H-interaction']}**."]
    return "\n".join(lines) + "\n"


if __name__ == "__main__" and len(sys.argv) > 1 and sys.argv[1] == "summarise":
    text = summarise(Path(sys.argv[2]))
    if len(sys.argv) > 3:
        Path(sys.argv[3]).write_text(text)
    print(text)
    raise SystemExit(0)

# Capture this script's own arguments before sys.argv is replaced with the sweep's.
ARGS = list(sys.argv)
AXES, OUT = ARGS[1], Path(ARGS[2])
KEEP = {"none": (), "x": (0,), "y": (1,), "z": (2,), "all": (0, 1, 2)}[AXES]
OFF = np.array([0.0 if k in KEEP else 1.0 for k in range(3)])   # 1 = remove on this axis

sys.argv = ["sweep", "--completion", "strict", "--speed-lo", "2", "--speed-hi", "12",
            "--speed-cap", "25", "--speed-tol", "0.0625", "--att-omega-n", "24",
            "--pos-omega-n", "2.0", "--pos-zeta", "1.0", "--feedforward", "--max-accel", "40"]
import importlib.util  # noqa: E402

sys.path.insert(0, str(REPO / "examples" / "spear"))
spec = importlib.util.spec_from_file_location(
    "sweep", REPO / "examples" / "spear" / "19_morphology_design_sweep.py")
sweep = importlib.util.module_from_spec(spec)
sys.modules["sweep"] = sweep
spec.loader.exec_module(sweep)

import ariel.simulation.drone.controllers.lee_control.base_lee_controller as blc  # noqa: E402
import ariel.simulation.drone.drone_simulator as ds  # noqa: E402
from ariel.body_phenotypes.drone.backends import blueprint_to_propellers  # noqa: E402
from ariel.body_phenotypes.drone.decoders import spherical_angular_to_blueprint  # noqa: E402
from ariel.simulation.tasks.slalom_course import slalom_gates  # noqa: E402

calls = {"plant": 0, "ctrl": 0}
errors: list[str] = []
_orig_setup = ds.DroneSimulator._setup_dynamics


def _setup(self) -> None:
    _orig_setup(self)
    f = self.dynamics_func
    inertia = np.asarray(self.params["inertia"], dtype=float)
    inv = np.linalg.inv(inertia)

    def g(state, action):
        calls["plant"] += 1
        try:
            out = np.array(f(state, action), dtype=float)
            w = np.asarray(state[9:12], dtype=float)
            # The plant integrates -I^-1 (w x Iw); adding back the OFF components
            # removes the term on those axes (I is diagonal for this family).
            out[9:12] += inv @ (OFF * np.cross(w, inertia @ w))
        except Exception as e:           # rollout() swallows exceptions; keep a record
            errors.append(repr(e))
            raise
        return out

    self.dynamics_func = g


_orig_torque = blc.BaseLeeController.compute_body_torque


def _torque(self, *a, **kw):
    calls["ctrl"] += 1
    try:
        tau = np.asarray(_orig_torque(self, *a, **kw), dtype=float)
        w = np.asarray(self.robot_body_angvel, dtype=float)
        return tau - OFF * np.cross(w, np.asarray(self.robot_inertia, dtype=float) @ w)
    except Exception as e:
        errors.append(repr(e))
        raise


ds.DroneSimulator._setup_dynamics = _setup
blc.BaseLeeController.compute_body_torque = _torque


def props_for(t_deg: float):
    return blueprint_to_propellers(
        spherical_angular_to_blueprint(sweep.make_genome(np.radians(t_deg)),
                                       propsize=sweep.PROP_SIZE), convention="ned")


# Instrument check, outside rollout()'s blanket except: a symmetric body at one
# steady motor speed has no net moment, so its angular acceleration at non-zero
# rates is exactly the kept gyroscopic components.
_sim = ds.DroneSimulator(propellers=props_for(20.44), payload_mass=sweep.PAYLOAD_MASS)
_p = _sim.params
_Wh = float(_p["W_hover"])
_x = np.zeros(12 + _sim.num_motors)
_x[9:12] = (4.0, -3.0, 2.0)
_x[12:] = 2.0 * (_Wh - ds.W_MIN_N) / (ds.W_MAX_N - ds.W_MIN_N) - 1.0
_u = np.full(_sim.num_motors,
             2.0 * ds._invert_sqrt_poly(_Wh, _p["w_max"], _p["w_min"], _p["k"]) - 1.0)
_I = np.asarray(_p["inertia"], dtype=float)
_got = np.asarray(_sim.dynamics_func(_x, _u), dtype=float).ravel()[9:12]
_want = -np.linalg.solve(_I, (1.0 - OFF) * np.cross(_x[9:12], _I @ _x[9:12]))
assert np.allclose(_got, _want, atol=1e-9), (_got, _want)
print(f"{AXES}: plant check ok, angular accel {np.round(_got, 3)}", flush=True)
calls["plant"] = 0

exact = sorted({float(r["half_angle_deg"]) for r in csv.DictReader(open(TABLE_CORRECTED))})
res: dict = json.loads(OUT.read_text()) if OUT.exists() else {}
for turn in TURNS:
    course = slalom_gates(turn, leg=sweep.args.leg, n_gates=sweep.args.n_gates,
                          gate_size=sweep.args.gate_size)
    for h in HALVES:
        t = next(e for e in exact if round(e, 2) == h)
        key = f"{turn:.0f}@{h:.2f}"
        if key in res:
            continue
        r = sweep.max_completing_speed(sweep.make_genome(np.radians(t)), course)
        assert calls["plant"] > 0 and calls["ctrl"] > 0, calls
        assert not errors, errors[:3]
        res[key] = {"max_speed": float(r["max_speed"]), "monotone": bool(r["monotone"]),
                    "bracket": str(r["bracket"])}
        OUT.write_text(json.dumps(res, indent=1))
        print(AXES, key, r["max_speed"], flush=True)
print("done", AXES, calls, flush=True)
